# Generated by `hip-cargo transpile` — do not edit.
# Source recipe: src/stokify/recipes/stokify.yml

"""Typer driver CLI for the 'stokify' pipeline."""

import uuid
from pathlib import Path
from typing import Annotated, NewType

import typer
from hip_cargo import parse_upath

Directory = NewType("Directory", Path)

app = typer.Typer(help="Transpiled driver for the 'stokify' recipe.")


@app.command()
def run(
    base_dir: Annotated[
        Directory,
        typer.Option(
            ...,
            parser=parse_upath,
            help="Base output directory for all data products.",
        ),
    ],
    memory_mode: Annotated[
        str,
        typer.Option(
            help="Memory mode: greedy (plasma-resident) or conservative (store-backed).",
        ),
    ] = "greedy",
    n_band: Annotated[
        int,
        typer.Option(
            help="",
        ),
    ] = 4,
    n_stokes: Annotated[
        int,
        typer.Option(
            help="",
        ),
    ] = 2,
    n_x: Annotated[
        int,
        typer.Option(
            help="",
        ),
    ] = 256,
    n_y: Annotated[
        int,
        typer.Option(
            help="",
        ),
    ] = 256,
    niter: Annotated[
        int,
        typer.Option(
            help="Iterations for the process and image steps.",
        ),
    ] = 10,
    monitor: Annotated[
        bool,
        typer.Option(
            help="Stream progress events to the monitoring aggregator.",
        ),
    ] = False,
    job_id: Annotated[
        str | None,
        typer.Option(
            help="Fixed job id (useful for following a run live).",
        ),
    ] = None,
    ray_address: Annotated[
        str | None,
        typer.Option(
            help="Ray cluster address; omit to start/use a local cluster.",
        ),
    ] = None,
):
    """Run the 'stokify' pipeline on a Ray cluster."""
    from stokify.transpiled.runner import run_pipeline

    if job_id is None:
        job_id = uuid.uuid4().hex[:8]
    typer.echo(f"job_id={job_id}")
    run_pipeline(
        base_dir=str(base_dir),
        memory_mode=memory_mode,
        n_band=n_band,
        n_stokes=n_stokes,
        n_x=n_x,
        n_y=n_y,
        niter=niter,
        monitor=monitor,
        job_id=job_id,
        ray_address=ray_address,
    )
    typer.echo(f"pipeline complete: job_id={job_id}")
