# Generated by `hip-cargo transpile` — do not edit.
# Source recipe: src/stokify/recipes/stokify.yml

"""ObjectRef-chaining pipeline runner for the 'stokify' recipe."""

import os

os.environ.setdefault("RAY_ENABLE_UV_RUN_RUNTIME_ENV", "0")

import uuid  # noqa: E402

from hip_cargo.utils.progress import EventType, ProgressEvent, emit  # noqa: E402

STEPS = ["init", "process", "image"]
EDGES = [["init", "process"], ["process", "image"]]


def _emit(event_type: EventType, job_id: str, worker_name: str, message: str = "", extra: dict | None = None) -> None:
    """Emit a pipeline-level event through the active backend."""
    emit(
        ProgressEvent(job_id=job_id, worker_name=worker_name, event_type=event_type, message=message, extra=extra or {})
    )


def run_pipeline(
    base_dir: str,
    memory_mode: str = "greedy",
    n_band: int = 4,
    n_stokes: int = 2,
    n_x: int = 256,
    n_y: int = 256,
    niter: int = 10,
    monitor: bool = False,
    job_id: str | None = None,
    ray_address: str | None = None,
) -> "tuple[str, object]":
    """Run the 'stokify' pipeline on a Ray cluster; returns (job_id, final ObjectRef)."""
    import ray

    from stokify.transpiled import tasks

    if job_id is None:
        job_id = uuid.uuid4().hex[:8]
    if not ray.is_initialized():
        ray.init(address=ray_address, namespace="stokify", ignore_reinit_error=True)
    if monitor:
        from hip_cargo.monitoring.ray_backend import RayProgressBackend, get_or_create_aggregator
        from hip_cargo.utils.progress import set_backend

        set_backend(RayProgressBackend(get_or_create_aggregator()))

    base_dir = str(base_dir)
    os.makedirs(base_dir, exist_ok=True)

    _emit(
        EventType.PIPELINE_STARTED,
        job_id,
        "stokify",
        message=f"memory_mode={memory_mode}",
        extra={"steps": STEPS, "edges": EDGES, "memory_mode": memory_mode},
    )

    _emit(EventType.STEP_STARTED, job_id, "init", extra={"step_index": 0})
    ref_init = tasks.init_task.remote(
        memory_mode, job_id, base_dir, monitor, n_band=n_band, n_stokes=n_stokes, n_x=n_x, n_y=n_y
    )
    ray.wait([ref_init])
    _emit(EventType.STEP_COMPLETED, job_id, "init", extra={"step_index": 0})

    _emit(EventType.STEP_STARTED, job_id, "process", extra={"step_index": 1})
    ref_process = tasks.process_task.remote(ref_init, memory_mode, job_id, base_dir, monitor, n_iterations=niter)
    ray.wait([ref_process])
    _emit(EventType.STEP_COMPLETED, job_id, "process", extra={"step_index": 1})

    _emit(EventType.STEP_STARTED, job_id, "image", extra={"step_index": 2})
    ref_image = tasks.image_task.remote(ref_process, memory_mode, job_id, base_dir, monitor, n_iterations=niter)
    ray.wait([ref_image])
    _emit(EventType.STEP_COMPLETED, job_id, "image", extra={"step_index": 2})

    _emit(EventType.COMPLETED, job_id, "stokify", message="pipeline complete")
    return job_id, ref_image
