# Generated by `hip-cargo transpile` — do not edit.
# Source recipe: src/stokify/recipes/stokify.yml

"""Per-step @ray.remote task wrappers for the 'stokify' pipeline."""

import os

os.environ.setdefault("RAY_ENABLE_UV_RUN_RUNTIME_ENV", "0")

import ray  # noqa: E402


def _activate_backend() -> None:
    """Register the shared aggregator backend inside this worker process."""
    from hip_cargo.monitoring.ray_backend import RayProgressBackend, get_or_create_aggregator
    from hip_cargo.utils.progress import set_backend

    set_backend(RayProgressBackend(get_or_create_aggregator()))


@ray.remote(num_cpus=0)
def _check(ref_holder: list) -> bool:
    """Surface a step's error without materialising its dataset on the driver.

    The ObjectRef arrives unresolved inside a list; ray.get here re-raises a
    failed step's exception, while a successful dataset deserialises in this
    zero-cpu worker (plasma-local), never in the lightweight driver.
    """
    ray.get(ref_holder[0])
    return True


@ray.remote
def init_task(
    memory_mode: str, job_id: str, work_dir: str, monitor: bool, n_band: int, n_stokes: int, n_x: int, n_y: int
) -> "object":
    """Run step 'init' (cab 'init') in-memory."""
    if monitor:
        _activate_backend()
    import time as _time

    _t0 = _time.perf_counter()
    from stokify.core.init import init_inmem

    if monitor:
        from hip_cargo.utils.diagnostics import annotate_diagnostics

        annotate_diagnostics(import_s=_time.perf_counter() - _t0, requested={"num_cpus": 1}, memory_mode=memory_mode)
    return init_inmem(memory_mode, job_id, job_id, work_dir, n_band=n_band, n_stokes=n_stokes, n_x=n_x, n_y=n_y)


@ray.remote
def process_task(
    dataset: "object", memory_mode: str, job_id: str, work_dir: str, monitor: bool, n_iterations: int
) -> "object":
    """Run step 'process' (cab 'process') in-memory."""
    if monitor:
        _activate_backend()
    import time as _time

    _t0 = _time.perf_counter()
    from stokify.core.process import process_inmem

    if monitor:
        from hip_cargo.utils.diagnostics import annotate_diagnostics

        annotate_diagnostics(import_s=_time.perf_counter() - _t0, requested={"num_cpus": 1}, memory_mode=memory_mode)
    return process_inmem(dataset, memory_mode, job_id, job_id, work_dir, n_iterations=n_iterations)


@ray.remote
def image_task(
    dataset: "object", memory_mode: str, job_id: str, work_dir: str, monitor: bool, n_iterations: int
) -> "object":
    """Run step 'image' (cab 'image') in-memory."""
    if monitor:
        _activate_backend()
    import time as _time

    _t0 = _time.perf_counter()
    from stokify.core.image import image_inmem

    if monitor:
        from hip_cargo.utils.diagnostics import annotate_diagnostics

        annotate_diagnostics(import_s=_time.perf_counter() - _t0, requested={"num_cpus": 1}, memory_mode=memory_mode)
    return image_inmem(dataset, memory_mode, job_id, job_id, work_dir, n_iterations=n_iterations)
